# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-msg" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "794b67309d118d5de9b9adc12fe5d65a8edb7f79edd6721511395d2ef7b20c85"
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
    end
    on_arm do
      sha256 "63fa27fd81f7735ac2c6164e6b026f775351a5421b910732c117ad61dd3031e8"
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
    end
  end

  on_linux do
    on_intel do
      sha256 "35c96f09bda31344bae9e87c71b474127182b1af60c2f15d6073bab88536be8a"
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
    end
    on_arm do
      sha256 "a80422ca384b657ac584c9cb475b584ee7f65e1bdcfad72171a5ff61ce608d74"
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
    end
  end

  name "git-msg"
  desc "AI-assisted git commit message generator with multi-provider LLM support"
  homepage "https://github.com/madstone-tech/git-msg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-msg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-msg"]
    end
  end

  # No zap stanza required

end
