# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-msg" do
  name "git-msg"
  desc "AI-assisted git commit message generator with multi-provider LLM support"
  homepage "https://github.com/madstone-tech/git-msg"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-msg"

  on_macos do
    on_intel do
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
      sha256 "a84ae689cbb2931d474ee8da9df9b670ba845d78384319724236d30dee1d06ee"
    end
    on_arm do
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
      sha256 "dd5222385cc6a37d804536e056747291fcf484648afd2fa7ebe92feef00ecf73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
      sha256 "526d30d632acaac2456ae68316f7c0b1fa393b341829e4c2135a6f474b8dc844"
    end
    on_arm do
      url "https://github.com/madstone-tech/git-msg/releases/download/v#{version}/git-msg_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/git-msg"
      sha256 "af0b4a8fce0c6899987d95a0db34d81599349b596cc84edb9cf2b248df003cf8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-msg"]
    end
  end

  # No zap stanza required
end
