# This file was generated by GoReleaser. DO NOT EDIT.
cask "loko" do
  name "loko"
  desc "Guardian of architectural wisdom - C4 model documentation with LLM integration"
  homepage "https://github.com/madstone-tech/loko"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loko"

  on_macos do
    on_intel do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "41fd3705ff7237de1d4a7da9c0d2c9eaecc154d379024a8d31d920e1972275af"
    end
    on_arm do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "79fe25e372e623c631c50dbffb75214173226dcdfa2e189c0b14c1d81039088f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "f1d58450071d105fee140b3a80d7fec7cf2c4ad72eaa5b17c5473151bae210f8"
    end
    on_arm do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "0cd6ea496beec8f8360e3e301acebde4bca83cbdaffdb117e8f9fb7960a0a8b3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loko"]
    end
  end

  # No zap stanza required
end
