# This file was generated by GoReleaser. DO NOT EDIT.
cask "loko" do
  name "loko"
  desc "Guardian of architectural wisdom - C4 model documentation with LLM integration"
  homepage "https://github.com/madstone-tech/loko"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loko"

  on_macos do
    on_intel do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "456993d3d962ad6049b47b003f287dd19d1d4ae2d4b6c019f6dcf4e121f6981e"
    end
    on_arm do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "51acff800fef9c9e55c76d8d4abf7cc3c4e868b62bf754c6c555490d75eaba90"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "c6b188bb7b48468c3d8d0f747e36dff9a312954059e90335ad913bd1884c506b"
    end
    on_arm do
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/loko"
      sha256 "01836bdd2b8d31c77c529035e370d0eb194269aca1b7183a264e55047c3986b1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loko"]
    end
  end

  # No zap stanza required
end
