# This file was generated by GoReleaser. DO NOT EDIT.
cask "loko" do
  version "1.0.0"

  on_macos do
    sha256 "c40634984e9c59326a0e0a05420eacf52ec72a72595fb3c8fc80c620e3b674da"
    url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "05a968f7a20b697888f3f4f8dce69dd069f07324fd655cc837cf43f7cd7c9229"
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b26cbb19919afc8463f4be192a6ee91bd1d77a553958813ecd3e6926d3f20c07"
      url "https://github.com/madstone-tech/loko/releases/download/v#{version}/loko_Linux_x86_64.tar.gz"
    end
  end

  name "loko"
  desc "Compile C4 software architecture from HCL into diagrams, docs and queries"
  homepage "https://github.com/madstone-tech/loko"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loko"]
    end
  end
  generate_completions_from_executable "loko",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
