# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdstn-cipher" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "b14b9c07b6248faeef482cae21da19c7c99b9bab1cbf00fc841a42203a637696"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
    on_arm do
      sha256 "835b4a1499281bf805a29887c7d27aa7bfae4930cc9d0b1e5400558510340be0"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
  end

  on_linux do
    on_intel do
      sha256 "77a619b9eee8dea77b202c6b020951aa580757bfd2db00378d45de48b140ac92"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
    on_arm do
      sha256 "cc9fc2c0bcac0d219540297c69fcae880ae8e89541f123ee192aa00d30bfbf63"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
  end

  name "mdstn-cipher"
  desc "File encryption and key management CLI"
  homepage "https://github.com/madstone-tech/cipher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdstn-cipher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdstn-cipher"]
    end
  end

  # No zap stanza required

end
