# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdstn-cipher" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "87b973f6619fbec134b7223eb1abc3df04bfb723d2b476f060d42c569c5fd437"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
    on_arm do
      sha256 "a63b70ea43207daf5af25e16720bd3d0e74f709bfa0ba765f0499ee66678ce69"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bf76d724e300d77c9dab2defa8cec2698732da00a57443b8c748aeca1c0cb5e"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
    on_arm do
      sha256 "5373f1be7da24a88e321559715f95602508a2a9a53e62b8bd2017408e19fa3cf"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
  end

  name "mdstn-cipher"
  desc "File encryption and key management CLI"
  homepage "https://github.com/madstone-tech/cipher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdstn-cipher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdstn-cipher"]
    end
  end

  # No zap stanza required

end
