# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdstn-cipher" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "3f8103fb230c69c34bfd7af1445d47fdd89ffa5a937e36b6cc2b0f6868c53ce8"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Darwin_x86_64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
    on_arm do
      sha256 "401436df3a54e9032e0823aeb27599fa5aec8a5467bf7a22bdf462c67dfc108c"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Darwin_arm64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
  end

  on_linux do
    on_intel do
      sha256 "c19c83dc6cdcee73c039de88b962d39fbc77778036bc528553bc5c284d6b0066"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Linux_x86_64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
    on_arm do
      sha256 "2fb0199df0a526af20d5f1b7e2bc49d66ebd0e9390ba7ec3b8921c9d0cd87fcf"
      url "https://github.com/madstone-tech/cipher/releases/download/v#{version}/mdstn-cipher_Linux_arm64.tar.gz",
        verified: "github.com/madstone-tech/cipher"
    end
  end

  name "mdstn-cipher"
  desc "File encryption and key management CLI"
  homepage "https://github.com/madstone-tech/cipher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdstn-cipher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdstn-cipher"]
    end
  end

  # No zap stanza required

end
