# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ason < Formula
  desc "※ The sacred rattle that transforms templates into living projects"
  homepage "https://github.com/madstone-tech/ason"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madstone-tech/ason/releases/download/v0.3.1/ason_Darwin_x86_64.tar.gz"
      sha256 "544135d56f8f0081d94d0d59537352f31c30166dd9ac958b24ab15dbf2208cf3"

      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madstone-tech/ason/releases/download/v0.3.1/ason_Darwin_arm64.tar.gz"
      sha256 "614d3e675adf0b84a3de72124105678dfdfa39833bf55f54d7db23c6b7a2f744"

      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/ason/releases/download/v0.3.1/ason_Linux_x86_64.tar.gz"
      sha256 "b79a21781bcd5be91e391864ffa769def900a2b6ce9dfb3a12b548dcef58da7a"
      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/ason/releases/download/v0.3.1/ason_Linux_arm64.tar.gz"
      sha256 "55aeba95112ac716633897974050554bf305fc05277affeb5bc01c1f8982938c"
      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
  end

  test do
    system "#{bin}/ason --version"
  end
end
