# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ason < Formula
  desc "※ The sacred rattle that transforms templates into living projects"
  homepage "https://github.com/madstone-tech/ason"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madstone-tech/ason/releases/download/v0.2.1/ason_Darwin_x86_64.tar.gz"
      sha256 "5db30cb82c8e4f97c5b641c5eb3d36fa42397412f8cf2e6c271cd6d94af3a9ae"

      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madstone-tech/ason/releases/download/v0.2.1/ason_Darwin_arm64.tar.gz"
      sha256 "be50201ae74bac8ffb31f1a3450611e889095437828d098d11fc80cbf9583f46"

      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/ason/releases/download/v0.2.1/ason_Linux_x86_64.tar.gz"
      sha256 "0a889ad87544a3c66407757495e361859c57523d8b88d040337c463885698545"
      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/ason/releases/download/v0.2.1/ason_Linux_arm64.tar.gz"
      sha256 "c705bcd6b68dc5bf7dd207333681df1f21f29ecfd3346921cdcd927cad51ea6c"
      def install
        bin.install "ason"

        # Generate and install shell completions
        bash_completion.install "completions/ason.bash" => "ason" if File.exist?("completions/ason.bash")
        zsh_completion.install "completions/_ason" if File.exist?("completions/_ason")
        fish_completion.install "completions/ason.fish" if File.exist?("completions/ason.fish")
      end
    end
  end

  test do
    system "#{bin}/ason --version"
  end
end
