# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbvault < Formula
  desc "Knowledge Base Vault CLI - A command-line tool for managing and searching your knowledge base"
  homepage "https://github.com/madstone-tech/mdstn-kb-mcp"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madstone-tech/mdstn-kb-mcp/releases/download/v1.0.0/kbvault_Darwin_x86_64.tar.gz"
      sha256 "3d2f8c4d7945fac8975f9f73e3a92ff462a1b03f673bfec5c981e9a697ce1b5c"

      def install
        bin.install "kbvault"

        # Generate and install shell completions
         bash_completion.install "completions/kbvault.bash" => "kbvault" if File.exist?("completions/kbvault.bash")
        zsh_completion.install "completions/_kbvault" if File.exist?("completions/_kbvault")
        fish_completion.install "completions/kbvault.fish" if File.exist?("completions/kbvault.fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madstone-tech/mdstn-kb-mcp/releases/download/v1.0.0/kbvault_Darwin_arm64.tar.gz"
      sha256 "037d6bfe14bdd503282ab75df4ed38b8dc503654ccee2e1471662627cda3cfcc"

      def install
        bin.install "kbvault"

        # Generate and install shell completions
         bash_completion.install "completions/kbvault.bash" => "kbvault" if File.exist?("completions/kbvault.bash")
        zsh_completion.install "completions/_kbvault" if File.exist?("completions/_kbvault")
        fish_completion.install "completions/kbvault.fish" if File.exist?("completions/kbvault.fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/mdstn-kb-mcp/releases/download/v1.0.0/kbvault_Linux_x86_64.tar.gz"
      sha256 "a8d097e29a84b1dffba9cc99e0c20528daa91d2fd1a52a8291ff5d3e62a6467a"
      def install
        bin.install "kbvault"

        # Generate and install shell completions
         bash_completion.install "completions/kbvault.bash" => "kbvault" if File.exist?("completions/kbvault.bash")
        zsh_completion.install "completions/_kbvault" if File.exist?("completions/_kbvault")
        fish_completion.install "completions/kbvault.fish" if File.exist?("completions/kbvault.fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/mdstn-kb-mcp/releases/download/v1.0.0/kbvault_Linux_arm64.tar.gz"
      sha256 "fed74f49a82711599581d5c6eefb850cac72b98b11fbbe0c80f79cc77320154b"
      def install
        bin.install "kbvault"

        # Generate and install shell completions
         bash_completion.install "completions/kbvault.bash" => "kbvault" if File.exist?("completions/kbvault.bash")
        zsh_completion.install "completions/_kbvault" if File.exist?("completions/_kbvault")
        fish_completion.install "completions/kbvault.fish" if File.exist?("completions/kbvault.fish")
      end
    end
  end

  test do
    system "#{bin}/kbvault --version"
  end
end
