# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VeveCli < Formula
  desc "Fast, themeable markdown to PDF converter with Pandoc"
  homepage "https://github.com/madstone-tech/veve-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.2.1/veve-cli_Darwin_x86_64.tar.gz"
      sha256 "3b30cb8a2cf8909c4f50880b62e03ec1f65512eeb0e1ab3c32bc36067368939a"

      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.2.1/veve-cli_Darwin_arm64.tar.gz"
      sha256 "490850ffe3f4d8b5c99290bd08681a77924a6c03d3b6bcfe7d39aacd3849f07b"

      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.2.1/veve-cli_Linux_x86_64.tar.gz"
      sha256 "8e4c079c5f32affc61a8aea54b2a1424189337d81f21dbd01be2051935449cda"
      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.2.1/veve-cli_Linux_arm64.tar.gz"
      sha256 "2cc2520e444e2919aee4db564106fb56d8e6b8cebfd3b20346c79fc8afbc9653"
      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
  end

  test do
    system "#{bin}/veve --version"
  end
end
