# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VeveCli < Formula
  desc "Fast, themeable markdown to PDF converter with Pandoc"
  homepage "https://github.com/madstone-tech/veve-cli"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.9.1/veve-cli_Darwin_x86_64.tar.gz"
      sha256 "073678b3ecfaaf362b8c6b73f8bba33ddc21bfc6af72c688407852fedc5c9226"

      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.9.1/veve-cli_Darwin_arm64.tar.gz"
      sha256 "123719b1162d5cb40a502126e74fe1c5414bbb579d42efe5041e20bbd7802685"

      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.9.1/veve-cli_Linux_x86_64.tar.gz"
      sha256 "cbdc71403319afc317c68210e1f5deceb5a3071d8d0a4fea6f043f6d1f71af68"
      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/madstone-tech/veve-cli/releases/download/v0.9.1/veve-cli_Linux_arm64.tar.gz"
      sha256 "a8b8687834a27bee2a3957f7e614c5530af8be29d75a8a98872b1b066a611b5e"
      def install
        bin.install "veve"

        # Generate and install shell completions
        bash_completion.install "completions/veve.bash" => "veve" if File.exist?("completions/veve.bash")
        zsh_completion.install "completions/_veve" if File.exist?("completions/_veve")
        fish_completion.install "completions/veve.fish" if File.exist?("completions/veve.fish")
      end
    end
  end

  test do
    system "#{bin}/veve --version"
  end
end
